"""empty message

Revision ID: 1ae41d5e4193
Revises: 
Create Date: 2017-04-04 14:59:36.860566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae41d5e4193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page2_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('Page2Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Page2singleTransMoney', sa.Float(), nullable=True),
    sa.Column('Page2favOrgName', sa.String(length=30), nullable=True),
    sa.Column('Page2favOrgNameCount', sa.Integer(), nullable=True),
    sa.Column('Page2favOrgNameTotalTransMoney', sa.Integer(), nullable=True),
    sa.Column('Page2totalRefectoryConsumed', sa.Float(), nullable=True),
    sa.Column('Page2Rian', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_page2_data_userId'), 'page2_data', ['userId'], unique=True)
    op.create_table('page3_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('Page3Timestamp', sa.DateTime(), nullable=True),
    sa.Column('Page3totalTransMoney', sa.Float(), nullable=True),
    sa.Column('Page3totalShoppingCount', sa.Integer(), nullable=True),
    sa.Column('Page3totalShoppingConsumed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_page3_data_userId'), 'page3_data', ['userId'], unique=True)
    op.create_table('page4_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('Page4RichMonthConsum', sa.Float(), nullable=True),
    sa.Column('Page4PoorMonthConsum', sa.Float(), nullable=True),
    sa.Column('Page4RichMonth', sa.Integer(), nullable=True),
    sa.Column('Page4PoorMonth', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('page5_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('Page5totalTransMoney', sa.Float(), nullable=True),
    sa.Column('Page5totalRefectoryTransMoney', sa.Float(), nullable=True),
    sa.Column('Page5totalShopTransMoney', sa.Float(), nullable=True),
    sa.Column('Page5RankTheWholeSchool', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('stdcc_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('orgName', sa.String(length=50), nullable=True),
    sa.Column('userName', sa.String(length=20), nullable=True),
    sa.Column('dealDateTimestamp', sa.DateTime(), nullable=True),
    sa.Column('dealDate', sa.String(length=20), nullable=True),
    sa.Column('dealTime', sa.String(length=20), nullable=True),
    sa.Column('transMoney', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8'
    )
    op.create_index(op.f('ix_stdcc_table_dealDateTimestamp'), 'stdcc_table', ['dealDateTimestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stdcc_table_dealDateTimestamp'), table_name='stdcc_table')
    op.drop_table('stdcc_table')
    op.drop_table('page5_data')
    op.drop_table('page4_data')
    op.drop_index(op.f('ix_page3_data_userId'), table_name='page3_data')
    op.drop_table('page3_data')
    op.drop_index(op.f('ix_page2_data_userId'), table_name='page2_data')
    op.drop_table('page2_data')
    # ### end Alembic commands ###
